### ISSUE TITLE
expressKerberos is not a function

### ISSUE THREAD

**Issue by karousn** [noamokman/express-kerberos#1]
the propose implementation throw this message error !
any dependency i should install it ?

**Comment by noamokman** [comment]
From what I understand, it seems that you are using `require` and not `import`.
If you want to use `require` please use the `default` value from the returned value.
If this is not the case, please paste the code you are trying to use.

**Comment by ryanvgates** [comment]
@noamokman can you provide a code example for what you mean by using the default value? I'm using the code from npm https://www.npmjs.com/package/express-kerberos

```
var express = require('express');
var expressKerberos = require('express-kerberos');
 
const app = express();
 
app.get('/', expressKerberos(), (req, res) => {
  res.send(`Hello ${req.auth.username}!`);
});
```

**Comment by noamokman** [comment]
Hi @ryanvgates,
> If you want to use `require` please use the `default` value from the returned value.

```js
var express = require('express');
var {default: expressKerberos} = require('express-kerberos');
 
const app = express();
 
app.get('/', expressKerberos(), (req, res) => {
  res.send(`Hello ${req.auth.username}!`);
});
```
this should work.
This happens because of how babel transpile to commonjs

**Comment by ryanvgates** [comment]
This worked for me. Thank you for your help @noamokman
