### ISSUE TITLE
Simple Kerberos failed to load the "kerberos" module

### ISSUE THREAD

**Issue by JumpAttacker** [noamokman/express-kerberos#4]
![image](https://user-images.githubusercontent.com/10989729/67867280-373e9000-fb3b-11e9-8b16-28a53931d822.png)

What i did:

Linux

 * python v2.7
 * make
 * A proper C/C++ compiler toolchain, like GCC
 * Distribution-specific kerberos packages (e.g. krb5-dev on Ubuntu)

then type

npm install express-kerberos --unsafe-perm

and got this error now

**Comment by JumpAttacker** [comment]
hm, did install express-auth-negotiate +simple-kerberos
and now got new error with dat code
```
const express = require('express');
const expressKerberos = require('express-kerberos');

const app = express();

app.get('/', expressKerberos(), (req, res) => {
  res.send(`Hello ${req.auth.username}!`);
});
let fs = require("fs");
let https = require("https");
let privateKey = fs.readFileSync("./server.key", "utf8");
let certificate = fs.readFileSync("./server.crt", "utf8");
let credentials = { key: privateKey, cert: certificate };
let httpsServer = https.createServer(credentials, app);
httpsServer.listen(3300, ()=> {
  console.log('listen');
});
```

![image](https://user-images.githubusercontent.com/10989729/67933062-20994700-fbd6-11e9-9c4e-9881d708a5cd.png)

**Comment by JumpAttacker** [comment]
just changed 
```
const expressKerberos = require('express-kerberos'); 
```
to 
```
const expressKerberos = require('express-kerberos').default;
```
and now server is working fine

but now when i try to connect to dat server i got an error

![image](https://user-images.githubusercontent.com/10989729/67933464-e4b2b180-fbd6-11e9-88fd-20f30597a6c3.png)

**Comment by JumpAttacker** [comment]
just added my server to AD and created .keytab file 
and all working fine now.

But one another question: how can i get user's sid? Is it possible with dat lib?

**Comment by noamokman** [comment]
no, this lib is only a wrapper to the kerberos module
