### ISSUE TITLE
TypeError: kerberosModule.Kerberos is not a constructor

### ISSUE THREAD

**Issue by alljinx** [noamokman/express-kerberos#8]
I'm sorry, I know some similars was already closed but I can't make it work...

```
var express = require('express');
var expressKerberos = require('express-kerberos').default;
// var {default: expressKerberos} = require('express-kerberos'); // I tried this too, without success
 
const app = express();
 
app.get('/', expressKerberos(), (req, res) => {
  res.send(`Hello ${req.auth.username}!`);
});
```

![image](https://user-images.githubusercontent.com/42472198/95825576-5bd24e80-0d31-11eb-98e6-123baee8870f.png)

Any clue ?

**Comment by noamokman** [comment]
hmm looks like the last package update in simple-kerberos broke the package.
Sadly I don't use it anymore and can't test it.
We need to fix the base package and update the version here.
If you can, open a PR on the simple-kerberos repo

**Comment by alljinx** [comment]
Ok thx for your time.
